# Site settings
email: 
baseurl: "https://novacane.github.io/R_ALONSO/"
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics: 

# SEO settings
title: RoAlonso
description: Codes like a romantic teen
url: ""
twitter_username: "https://twitter.com/hiimakodama"
default_img: 

# Profile settings
name: RoAlonso
profile_img: "https://pbs.twimg.com/profile_images/836291006798639105/PlyZXwTL_400x400.jpg"
profile: 21 is the leng of my array list of years, code editor ##ATOM , happines lives in 15. Not all is about 0 and 1
social:
  github: "https://github.com/novacane"
  instagram: "https://www.instagram.com/merumlda_lovelace"

# Build settings
exclude: ["_screenshots", "Gemfile", "Gemfile.lock", "LICENSE.txt", "README.md"]
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]
